package com.resume.dashboard.entity;

public enum ProfessionCategory {
    PROFESSIONAL_CORPORATE,
    TECH_ENGINEERING,
    DESIGN_CREATIVE,
    ARTIST_ILLUSTRATION,
    PHOTOGRAPHY_FILM,
    WRITING_PUBLISHING,
    HEALTHCARE_MEDICAL,
    LEGAL_PUBLIC_POLICY,
    FINANCE_BUSINESS,
    EDUCATION_RESEARCH,
    MARKETING_SALES,
    CONSULTING_COACHING,
    HOSPITALITY_EVENTS,
    REAL_ESTATE_ARCHITECTURE,
    MEDIA_ENTERTAINMENT,
    NONPROFIT_SOCIAL_IMPACT,
    STUDENT_EARLY_CAREER
}
