server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/resume_dashboard


app.jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGp3dCBzZWNyZXQga2V5IGZvciByZXN1bWUgZGFzaGJvYXJkIHNhYXM=
app.jwt.expiration-ms=86400000
app.upload.dir=uploads


# ==============================
# CLOUDINARY CONFIG
# ==============================

cloudinary.cloud-name=Root
cloudinary.api-key=483113696698738
cloudinary.api-secret=Vg7O79P9DVN2vitLtzUoey09v5E